stages:
  - docu
docu:
  stage: docu
  tags:
     - shell
  only:
    refs:
     - master
  script:
     - doxygen docs/doxyfile
     - rm -rf /srv/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
     - mkdir -p /srv/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
     - mv html/* /srv/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
     - rm -rf *
